strict: true
site_name: Anki Community Wiki
site_description: A centeralised wiki all about the Anki Community.
site_author: Anki Community
site_url: https://ankicommunity.github.io/
repo_url: https://github.com/ankicommunity/ankicommunity.github.io
docs_dir: src
site_dir: build
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  favicon: favicon.ico
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - admonition
nav:
  - Welcome: 'index.md'
  - News: 'news.md'
  - Projects:
    - Anki Sync Server: 'projects/anki-sync-server.md'
    - Sync Redirector: 'projects/sync-redirector.md'
  - Tutorials:
    - Index: 'tutorials/index.md'
    - Docker:
      - 'tutorials/docker/how-to.md'
      - 'tutorials/docker/how-to-recompiling.md'
    - Encryption with proxy:
      - 'tutorials/encryption-with-proxy/apache.md'
    - 'tutorials/anki-custom-sync-server.md'
  - Contact Us: 'contact-us/index.md'