site_name: Anki Community Wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  favicon: favicon.ico

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
