site_name: Anki Community Wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  favicon: favicon.ico

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - admonition


nav:
  - Welcome: 'index.md'
  - Projects:
    - anki-sync-server: 'Projects/anki-sync-server.md'
    - SyncRedirector: 'Projects/SyncRedirector.md'
  - Tutorials:
    - Index: 'Tutorials/Index.md'
    - Docker:
      - 'Tutorials/Docker/Howto.md'
      - 'Tutorials/Docker/Howto_Recompiling.md'
    - Encryption with proxy:
      - 'Tutorials/Encryption with proxy/Apache.md'
    - 'Tutorials/anki_custom_sync_server.md'
  - How to contact us:
     - 'How to contact us/our_forums.md'

